name: Render and Deploy

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # 1) Instalar R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      # 2) Instalar paquetes de R necesarios
      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::knitr
            any::rmarkdown
      
            # Tidyverse y manipulación
            any::tidyverse
            any::data.table
            any::janitor
            any::lubridate
      
            # Tablas y reporte
            any::modelsummary
            any::gt
            any::kableExtra
            any::broom
      
            # Econometría clásica
            any::sandwich
            any::lmtest
            any::AER
            any::fixest
            any::clubSandwich
            any::estimatr
      
            # Panel data
            any::plm
      
            # Series de tiempo
            any::tsibble
            any::tsibbledata
            any::fable
            any::fabletools
            any::forecast
            any::vars
            any::urca
            any::tseries
      
            # Causalidad / microeconometría
            any::MatchIt
            any::marginaleffects
            any::pscl
            any::survival
      
            # Datasets útiles
            any::wooldridge
            any::Ecdat


      # 3) Instalar Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 'release'

      # 4) Renderizar el proyecto Quarto 
      - name: Render Quarto Project
        run: quarto render

      # 5) Publicar en GitHub Pages (usando la carpeta _book)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book

